head.load("js/lib/jquery.js", 
					"js/lib/cycle.js",
					"js/common.js",
                    "js/lib/jquery.validate.js",
                    "js/lib/cycle.carousel.js",
                    "js/lib/jquery.fancybox.pack.js",
                    "js/lib/jquery.form.js",
                    "js/lib/jquery.stellar.min.js",
                    "js/lib/jquery.reel-min.js"
                     );
